name: Manual workflow

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      datetest:
        description: "Enter date"
        required: true


jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: checkout branch
      uses: actions/checkout@v2
      id: checkout_branch
      with:
        ref: "source1"
    - name: create PR
      id: create_pr
      with:
        commit-message: "message test"
        committer: "Ken Ellorando <kenellorando@gmail.com>"
        author: "Ken Ellorando <kenellorando@gmail.com>"
        signoff: false
        base: source1
        branch: new1-${{ github.event.inputs.datetest }}
        delete-branch: false
        title: 'automated pr test'
        body: |
          automated pr test body
        assignees: kenellorando
    
