name: Manual workflow

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      datetest:
        description: "Enter date"
        required: true


jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    # checkout "source1"
    - name: checkout branch
      uses: actions/checkout@v2
      id: checkout_branch
      with:
        ref: "source1"
        fetch-depth: 0
    # create a new branch (from source1) using the date input
    - name: create datetest branch
      id: create_datetest_branch
      uses: peterjgrainger/action-create-branch@v2.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        branch: new1-${{ github.event.inputs.datetest }}
    # create a PR of the new branch pointed towards master
    - name: create PR
      uses: peter-evans/create-pull-request@v3
      id: create_pr
      with:
        commit-message: "message test"
        committer: "Ken Ellorando <kenellorando@gmail.com>"
        author: "Ken Ellorando <kenellorando@gmail.com>"
        signoff: false
        base: new1-${{ github.event.inputs.datetest }}
        branch: master
        delete-branch: false
        title: 'automated pr test'
        body: |
          automated pr test body
        assignees: kenellorando
