name: Manual workflow

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      datetest:
        description: "Enter date"
        required: true


jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    # checkout "source1"
    - name: checkout branch
      uses: actions/checkout@v2
      id: checkout_branch
      with:
        ref: "source1"
        fetch-depth: 0
    # create a new branch (from source1) using the date input
    - name: create datetest branch
      id: create_datetest_branch
      uses: peterjgrainger/action-create-branch@v2.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        branch: new1-${{ github.event.inputs.datetest }}
    - run: |
        git push
    # create a PR of the new branch pointed towards master
    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        source_branch: new1-${{ github.event.inputs.datetest }}
        destination_branch: "master"
        github_token: ${{ secrets.GITHUB_TOKEN }}
        pr_label: "feature, automated pr"
        pr_title: "Automated PR test"
        pr_body: "Automated PR test body*"      
        pr_reviewer: "kenellorando"
        pr_assignee: "kenellorando"
        pr_allow_empty: true    
